/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    }
}
